# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gmain.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MWindow(object):
    def setupUi(self, MWindow):
        MWindow.setObjectName(_fromUtf8("MWindow"))
        MWindow.resize(823, 618)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(14)
        MWindow.setFont(font)
        MWindow.setStatusTip(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtGui.QFrame.StyledPanel)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 803, 598))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem = QtGui.QSpacerItem(759, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 5, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(759, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(759, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 1, 1, 1)
        self.act_task_1 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.act_task_1.setText(_fromUtf8(""))
        self.act_task_1.setObjectName(_fromUtf8("act_task_1"))
        self.gridLayout_2.addWidget(self.act_task_1, 0, 0, 1, 1)
        self.task_frame_1 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.task_frame_1.setEnabled(False)
        self.task_frame_1.setMinimumSize(QtCore.QSize(742, 121))
        self.task_frame_1.setMaximumSize(QtCore.QSize(23323, 121))
        self.task_frame_1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.task_frame_1.setFrameShadow(QtGui.QFrame.Raised)
        self.task_frame_1.setLineWidth(1)
        self.task_frame_1.setMidLineWidth(0)
        self.task_frame_1.setObjectName(_fromUtf8("task_frame_1"))
        self.task_passed_h_1 = QtGui.QLabel(self.task_frame_1)
        self.task_passed_h_1.setGeometry(QtCore.QRect(130, 80, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(14)
        self.task_passed_h_1.setFont(font)
        self.task_passed_h_1.setStyleSheet(_fromUtf8("color: rgb(14, 159, 255);"))
        self.task_passed_h_1.setAlignment(QtCore.Qt.AlignCenter)
        self.task_passed_h_1.setObjectName(_fromUtf8("task_passed_h_1"))
        self.task_rem_h_1 = QtGui.QLabel(self.task_frame_1)
        self.task_rem_h_1.setGeometry(QtCore.QRect(380, 80, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(14)
        self.task_rem_h_1.setFont(font)
        self.task_rem_h_1.setAlignment(QtCore.Qt.AlignCenter)
        self.task_rem_h_1.setObjectName(_fromUtf8("task_rem_h_1"))
        self.progressBar_1 = QtGui.QProgressBar(self.task_frame_1)
        self.progressBar_1.setGeometry(QtCore.QRect(40, 50, 381, 31))
        self.progressBar_1.setMaximum(100)
        self.progressBar_1.setProperty("value", 0)
        self.progressBar_1.setInvertedAppearance(False)
        self.progressBar_1.setObjectName(_fromUtf8("progressBar_1"))
        self.new_time_1 = QtGui.QSpinBox(self.task_frame_1)
        self.new_time_1.setGeometry(QtCore.QRect(540, 50, 63, 29))
        self.new_time_1.setSuffix(_fromUtf8(""))
        self.new_time_1.setPrefix(_fromUtf8(""))
        self.new_time_1.setMinimum(15)
        self.new_time_1.setMaximum(180)
        self.new_time_1.setSingleStep(15)
        self.new_time_1.setProperty("value", 15)
        self.new_time_1.setObjectName(_fromUtf8("new_time_1"))
        self.add_new_time_1 = QtGui.QPushButton(self.task_frame_1)
        self.add_new_time_1.setGeometry(QtCore.QRect(640, 50, 71, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(12)
        self.add_new_time_1.setFont(font)
        self.add_new_time_1.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 0);"))
        self.add_new_time_1.setObjectName(_fromUtf8("add_new_time_1"))
        self.delete_task_1 = QtGui.QPushButton(self.task_frame_1)
        self.delete_task_1.setGeometry(QtCore.QRect(720, 0, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.delete_task_1.setFont(font)
        self.delete_task_1.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.delete_task_1.setCheckable(False)
        self.delete_task_1.setDefault(False)
        self.delete_task_1.setObjectName(_fromUtf8("delete_task_1"))
        self.task_rem_h_8 = QtGui.QLabel(self.task_frame_1)
        self.task_rem_h_8.setGeometry(QtCore.QRect(600, 50, 21, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(12)
        self.task_rem_h_8.setFont(font)
        self.task_rem_h_8.setAlignment(QtCore.Qt.AlignCenter)
        self.task_rem_h_8.setObjectName(_fromUtf8("task_rem_h_8"))
        self.task_passed_h_5 = QtGui.QLabel(self.task_frame_1)
        self.task_passed_h_5.setGeometry(QtCore.QRect(40, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(11)
        self.task_passed_h_5.setFont(font)
        self.task_passed_h_5.setStyleSheet(_fromUtf8("color: rgb(14, 159, 255);"))
        self.task_passed_h_5.setAlignment(QtCore.Qt.AlignCenter)
        self.task_passed_h_5.setObjectName(_fromUtf8("task_passed_h_5"))
        self.task_passed_h_6 = QtGui.QLabel(self.task_frame_1)
        self.task_passed_h_6.setGeometry(QtCore.QRect(270, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(11)
        self.task_passed_h_6.setFont(font)
        self.task_passed_h_6.setAlignment(QtCore.Qt.AlignCenter)
        self.task_passed_h_6.setObjectName(_fromUtf8("task_passed_h_6"))
        self.task_name_1 = QtGui.QLineEdit(self.task_frame_1)
        self.task_name_1.setEnabled(False)
        self.task_name_1.setGeometry(QtCore.QRect(10, 8, 241, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.task_name_1.setFont(font)
        self.task_name_1.setText(_fromUtf8(""))
        self.task_name_1.setMaxLength(100)
        self.task_name_1.setFrame(True)
        self.task_name_1.setCursorPosition(0)
        self.task_name_1.setReadOnly(True)
        self.task_name_1.setObjectName(_fromUtf8("task_name_1"))
        self.edit_task_name_1 = QtGui.QCheckBox(self.task_frame_1)
        self.edit_task_name_1.setGeometry(QtCore.QRect(250, 10, 21, 31))
        self.edit_task_name_1.setText(_fromUtf8(""))
        self.edit_task_name_1.setObjectName(_fromUtf8("edit_task_name_1"))
        self.gridLayout_2.addWidget(self.task_frame_1, 0, 1, 1, 1)
        self.act_task_3 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.act_task_3.setText(_fromUtf8(""))
        self.act_task_3.setObjectName(_fromUtf8("act_task_3"))
        self.gridLayout_2.addWidget(self.act_task_3, 4, 0, 1, 1)
        self.act_task_2 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.act_task_2.setText(_fromUtf8(""))
        self.act_task_2.setObjectName(_fromUtf8("act_task_2"))
        self.gridLayout_2.addWidget(self.act_task_2, 2, 0, 1, 1)
        self.act_task_4 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.act_task_4.setText(_fromUtf8(""))
        self.act_task_4.setObjectName(_fromUtf8("act_task_4"))
        self.gridLayout_2.addWidget(self.act_task_4, 6, 0, 1, 1)
        self.task_frame_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.task_frame_2.setEnabled(False)
        self.task_frame_2.setMinimumSize(QtCore.QSize(742, 121))
        self.task_frame_2.setMaximumSize(QtCore.QSize(23323, 121))
        self.task_frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.task_frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.task_frame_2.setLineWidth(1)
        self.task_frame_2.setMidLineWidth(0)
        self.task_frame_2.setObjectName(_fromUtf8("task_frame_2"))
        self.task_passed_h_2 = QtGui.QLabel(self.task_frame_2)
        self.task_passed_h_2.setGeometry(QtCore.QRect(130, 80, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(14)
        self.task_passed_h_2.setFont(font)
        self.task_passed_h_2.setStyleSheet(_fromUtf8("color: rgb(14, 159, 255);"))
        self.task_passed_h_2.setAlignment(QtCore.Qt.AlignCenter)
        self.task_passed_h_2.setObjectName(_fromUtf8("task_passed_h_2"))
        self.task_rem_h_2 = QtGui.QLabel(self.task_frame_2)
        self.task_rem_h_2.setGeometry(QtCore.QRect(380, 80, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(14)
        self.task_rem_h_2.setFont(font)
        self.task_rem_h_2.setAlignment(QtCore.Qt.AlignCenter)
        self.task_rem_h_2.setObjectName(_fromUtf8("task_rem_h_2"))
        self.progressBar_2 = QtGui.QProgressBar(self.task_frame_2)
        self.progressBar_2.setGeometry(QtCore.QRect(40, 50, 381, 31))
        self.progressBar_2.setMaximum(20)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setInvertedAppearance(False)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.new_time_2 = QtGui.QSpinBox(self.task_frame_2)
        self.new_time_2.setGeometry(QtCore.QRect(540, 50, 63, 29))
        self.new_time_2.setSuffix(_fromUtf8(""))
        self.new_time_2.setPrefix(_fromUtf8(""))
        self.new_time_2.setMinimum(15)
        self.new_time_2.setMaximum(180)
        self.new_time_2.setSingleStep(15)
        self.new_time_2.setProperty("value", 15)
        self.new_time_2.setObjectName(_fromUtf8("new_time_2"))
        self.add_new_time_2 = QtGui.QPushButton(self.task_frame_2)
        self.add_new_time_2.setGeometry(QtCore.QRect(640, 50, 71, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(12)
        self.add_new_time_2.setFont(font)
        self.add_new_time_2.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 0);"))
        self.add_new_time_2.setObjectName(_fromUtf8("add_new_time_2"))
        self.delete_task_2 = QtGui.QPushButton(self.task_frame_2)
        self.delete_task_2.setGeometry(QtCore.QRect(720, 0, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.delete_task_2.setFont(font)
        self.delete_task_2.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.delete_task_2.setCheckable(False)
        self.delete_task_2.setDefault(False)
        self.delete_task_2.setObjectName(_fromUtf8("delete_task_2"))
        self.task_rem_h_9 = QtGui.QLabel(self.task_frame_2)
        self.task_rem_h_9.setGeometry(QtCore.QRect(600, 50, 21, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(12)
        self.task_rem_h_9.setFont(font)
        self.task_rem_h_9.setAlignment(QtCore.Qt.AlignCenter)
        self.task_rem_h_9.setObjectName(_fromUtf8("task_rem_h_9"))
        self.task_passed_h_7 = QtGui.QLabel(self.task_frame_2)
        self.task_passed_h_7.setGeometry(QtCore.QRect(40, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(11)
        self.task_passed_h_7.setFont(font)
        self.task_passed_h_7.setStyleSheet(_fromUtf8("color: rgb(14, 159, 255);"))
        self.task_passed_h_7.setAlignment(QtCore.Qt.AlignCenter)
        self.task_passed_h_7.setObjectName(_fromUtf8("task_passed_h_7"))
        self.task_passed_h_8 = QtGui.QLabel(self.task_frame_2)
        self.task_passed_h_8.setGeometry(QtCore.QRect(270, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(11)
        self.task_passed_h_8.setFont(font)
        self.task_passed_h_8.setAlignment(QtCore.Qt.AlignCenter)
        self.task_passed_h_8.setObjectName(_fromUtf8("task_passed_h_8"))
        self.task_name_2 = QtGui.QLineEdit(self.task_frame_2)
        self.task_name_2.setEnabled(False)
        self.task_name_2.setGeometry(QtCore.QRect(10, 8, 241, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.task_name_2.setFont(font)
        self.task_name_2.setText(_fromUtf8(""))
        self.task_name_2.setMaxLength(100)
        self.task_name_2.setFrame(True)
        self.task_name_2.setCursorPosition(0)
        self.task_name_2.setReadOnly(True)
        self.task_name_2.setObjectName(_fromUtf8("task_name_2"))
        self.edit_task_name_2 = QtGui.QCheckBox(self.task_frame_2)
        self.edit_task_name_2.setGeometry(QtCore.QRect(250, 10, 21, 31))
        self.edit_task_name_2.setText(_fromUtf8(""))
        self.edit_task_name_2.setObjectName(_fromUtf8("edit_task_name_2"))
        self.gridLayout_2.addWidget(self.task_frame_2, 2, 1, 1, 1)
        self.task_frame_3 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.task_frame_3.setEnabled(False)
        self.task_frame_3.setMinimumSize(QtCore.QSize(742, 121))
        self.task_frame_3.setMaximumSize(QtCore.QSize(23323, 121))
        self.task_frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.task_frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.task_frame_3.setLineWidth(1)
        self.task_frame_3.setMidLineWidth(0)
        self.task_frame_3.setObjectName(_fromUtf8("task_frame_3"))
        self.task_passed_h_3 = QtGui.QLabel(self.task_frame_3)
        self.task_passed_h_3.setGeometry(QtCore.QRect(130, 80, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(14)
        self.task_passed_h_3.setFont(font)
        self.task_passed_h_3.setStyleSheet(_fromUtf8("color: rgb(14, 159, 255);"))
        self.task_passed_h_3.setAlignment(QtCore.Qt.AlignCenter)
        self.task_passed_h_3.setObjectName(_fromUtf8("task_passed_h_3"))
        self.task_rem_h_3 = QtGui.QLabel(self.task_frame_3)
        self.task_rem_h_3.setGeometry(QtCore.QRect(380, 80, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(14)
        self.task_rem_h_3.setFont(font)
        self.task_rem_h_3.setAlignment(QtCore.Qt.AlignCenter)
        self.task_rem_h_3.setObjectName(_fromUtf8("task_rem_h_3"))
        self.progressBar_3 = QtGui.QProgressBar(self.task_frame_3)
        self.progressBar_3.setGeometry(QtCore.QRect(40, 50, 381, 31))
        self.progressBar_3.setMaximum(20)
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setInvertedAppearance(False)
        self.progressBar_3.setObjectName(_fromUtf8("progressBar_3"))
        self.new_time_3 = QtGui.QSpinBox(self.task_frame_3)
        self.new_time_3.setGeometry(QtCore.QRect(540, 50, 63, 29))
        self.new_time_3.setSuffix(_fromUtf8(""))
        self.new_time_3.setPrefix(_fromUtf8(""))
        self.new_time_3.setMinimum(15)
        self.new_time_3.setMaximum(180)
        self.new_time_3.setSingleStep(15)
        self.new_time_3.setProperty("value", 15)
        self.new_time_3.setObjectName(_fromUtf8("new_time_3"))
        self.add_new_time_3 = QtGui.QPushButton(self.task_frame_3)
        self.add_new_time_3.setGeometry(QtCore.QRect(640, 50, 71, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(12)
        self.add_new_time_3.setFont(font)
        self.add_new_time_3.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 0);"))
        self.add_new_time_3.setObjectName(_fromUtf8("add_new_time_3"))
        self.delete_task_3 = QtGui.QPushButton(self.task_frame_3)
        self.delete_task_3.setGeometry(QtCore.QRect(720, 0, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.delete_task_3.setFont(font)
        self.delete_task_3.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.delete_task_3.setCheckable(False)
        self.delete_task_3.setDefault(False)
        self.delete_task_3.setObjectName(_fromUtf8("delete_task_3"))
        self.task_rem_h_10 = QtGui.QLabel(self.task_frame_3)
        self.task_rem_h_10.setGeometry(QtCore.QRect(600, 50, 21, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(12)
        self.task_rem_h_10.setFont(font)
        self.task_rem_h_10.setAlignment(QtCore.Qt.AlignCenter)
        self.task_rem_h_10.setObjectName(_fromUtf8("task_rem_h_10"))
        self.task_passed_h_9 = QtGui.QLabel(self.task_frame_3)
        self.task_passed_h_9.setGeometry(QtCore.QRect(40, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(11)
        self.task_passed_h_9.setFont(font)
        self.task_passed_h_9.setStyleSheet(_fromUtf8("color: rgb(14, 159, 255);"))
        self.task_passed_h_9.setAlignment(QtCore.Qt.AlignCenter)
        self.task_passed_h_9.setObjectName(_fromUtf8("task_passed_h_9"))
        self.task_passed_h_10 = QtGui.QLabel(self.task_frame_3)
        self.task_passed_h_10.setGeometry(QtCore.QRect(270, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(11)
        self.task_passed_h_10.setFont(font)
        self.task_passed_h_10.setAlignment(QtCore.Qt.AlignCenter)
        self.task_passed_h_10.setObjectName(_fromUtf8("task_passed_h_10"))
        self.task_name_3 = QtGui.QLineEdit(self.task_frame_3)
        self.task_name_3.setEnabled(False)
        self.task_name_3.setGeometry(QtCore.QRect(10, 8, 241, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.task_name_3.setFont(font)
        self.task_name_3.setText(_fromUtf8(""))
        self.task_name_3.setMaxLength(100)
        self.task_name_3.setFrame(True)
        self.task_name_3.setCursorPosition(0)
        self.task_name_3.setReadOnly(True)
        self.task_name_3.setObjectName(_fromUtf8("task_name_3"))
        self.edit_task_name_3 = QtGui.QCheckBox(self.task_frame_3)
        self.edit_task_name_3.setGeometry(QtCore.QRect(250, 10, 21, 31))
        self.edit_task_name_3.setText(_fromUtf8(""))
        self.edit_task_name_3.setObjectName(_fromUtf8("edit_task_name_3"))
        self.gridLayout_2.addWidget(self.task_frame_3, 4, 1, 1, 1)
        self.task_frame_4 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.task_frame_4.setEnabled(False)
        self.task_frame_4.setMinimumSize(QtCore.QSize(742, 121))
        self.task_frame_4.setMaximumSize(QtCore.QSize(23323, 121))
        self.task_frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.task_frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.task_frame_4.setLineWidth(1)
        self.task_frame_4.setMidLineWidth(0)
        self.task_frame_4.setObjectName(_fromUtf8("task_frame_4"))
        self.task_passed_h_4 = QtGui.QLabel(self.task_frame_4)
        self.task_passed_h_4.setGeometry(QtCore.QRect(130, 80, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(14)
        self.task_passed_h_4.setFont(font)
        self.task_passed_h_4.setStyleSheet(_fromUtf8("color: rgb(14, 159, 255);"))
        self.task_passed_h_4.setAlignment(QtCore.Qt.AlignCenter)
        self.task_passed_h_4.setObjectName(_fromUtf8("task_passed_h_4"))
        self.task_rem_h_4 = QtGui.QLabel(self.task_frame_4)
        self.task_rem_h_4.setGeometry(QtCore.QRect(380, 80, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(14)
        self.task_rem_h_4.setFont(font)
        self.task_rem_h_4.setAlignment(QtCore.Qt.AlignCenter)
        self.task_rem_h_4.setObjectName(_fromUtf8("task_rem_h_4"))
        self.progressBar_4 = QtGui.QProgressBar(self.task_frame_4)
        self.progressBar_4.setGeometry(QtCore.QRect(40, 50, 381, 31))
        self.progressBar_4.setMaximum(20)
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setInvertedAppearance(False)
        self.progressBar_4.setObjectName(_fromUtf8("progressBar_4"))
        self.new_time_4 = QtGui.QSpinBox(self.task_frame_4)
        self.new_time_4.setGeometry(QtCore.QRect(540, 50, 63, 29))
        self.new_time_4.setSuffix(_fromUtf8(""))
        self.new_time_4.setPrefix(_fromUtf8(""))
        self.new_time_4.setMinimum(15)
        self.new_time_4.setMaximum(180)
        self.new_time_4.setSingleStep(15)
        self.new_time_4.setProperty("value", 15)
        self.new_time_4.setObjectName(_fromUtf8("new_time_4"))
        self.add_new_time_4 = QtGui.QPushButton(self.task_frame_4)
        self.add_new_time_4.setGeometry(QtCore.QRect(640, 50, 71, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(12)
        self.add_new_time_4.setFont(font)
        self.add_new_time_4.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 0);"))
        self.add_new_time_4.setObjectName(_fromUtf8("add_new_time_4"))
        self.delete_task_4 = QtGui.QPushButton(self.task_frame_4)
        self.delete_task_4.setGeometry(QtCore.QRect(720, 0, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.delete_task_4.setFont(font)
        self.delete_task_4.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.delete_task_4.setCheckable(False)
        self.delete_task_4.setDefault(False)
        self.delete_task_4.setObjectName(_fromUtf8("delete_task_4"))
        self.task_rem_h_11 = QtGui.QLabel(self.task_frame_4)
        self.task_rem_h_11.setGeometry(QtCore.QRect(600, 50, 21, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(12)
        self.task_rem_h_11.setFont(font)
        self.task_rem_h_11.setAlignment(QtCore.Qt.AlignCenter)
        self.task_rem_h_11.setObjectName(_fromUtf8("task_rem_h_11"))
        self.task_passed_h_11 = QtGui.QLabel(self.task_frame_4)
        self.task_passed_h_11.setGeometry(QtCore.QRect(40, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(11)
        self.task_passed_h_11.setFont(font)
        self.task_passed_h_11.setStyleSheet(_fromUtf8("color: rgb(14, 159, 255);"))
        self.task_passed_h_11.setAlignment(QtCore.Qt.AlignCenter)
        self.task_passed_h_11.setObjectName(_fromUtf8("task_passed_h_11"))
        self.task_passed_h_12 = QtGui.QLabel(self.task_frame_4)
        self.task_passed_h_12.setGeometry(QtCore.QRect(270, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("GE Inspira"))
        font.setPointSize(11)
        self.task_passed_h_12.setFont(font)
        self.task_passed_h_12.setAlignment(QtCore.Qt.AlignCenter)
        self.task_passed_h_12.setObjectName(_fromUtf8("task_passed_h_12"))
        self.task_name_4 = QtGui.QLineEdit(self.task_frame_4)
        self.task_name_4.setEnabled(False)
        self.task_name_4.setGeometry(QtCore.QRect(10, 8, 241, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.task_name_4.setFont(font)
        self.task_name_4.setText(_fromUtf8(""))
        self.task_name_4.setMaxLength(100)
        self.task_name_4.setFrame(True)
        self.task_name_4.setCursorPosition(0)
        self.task_name_4.setReadOnly(True)
        self.task_name_4.setObjectName(_fromUtf8("task_name_4"))
        self.edit_task_name_4 = QtGui.QCheckBox(self.task_frame_4)
        self.edit_task_name_4.setGeometry(QtCore.QRect(250, 10, 21, 31))
        self.edit_task_name_4.setText(_fromUtf8(""))
        self.edit_task_name_4.setObjectName(_fromUtf8("edit_task_name_4"))
        self.gridLayout_2.addWidget(self.task_frame_4, 6, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MWindow.setCentralWidget(self.centralwidget)
        self.actionNew_Task = QtGui.QAction(MWindow)
        self.actionNew_Task.setObjectName(_fromUtf8("actionNew_Task"))
        self.actionDelete_Task = QtGui.QAction(MWindow)
        self.actionDelete_Task.setObjectName(_fromUtf8("actionDelete_Task"))

        self.retranslateUi(MWindow)
        QtCore.QMetaObject.connectSlotsByName(MWindow)

    def retranslateUi(self, MWindow):
        MWindow.setWindowTitle(_translate("MWindow", "First 20 Hours of New Skills...", None))
        self.task_passed_h_1.setText(_translate("MWindow", "0", None))
        self.task_rem_h_1.setText(_translate("MWindow", "20", None))
        self.add_new_time_1.setText(_translate("MWindow", "Add Time", None))
        self.delete_task_1.setText(_translate("MWindow", "X", None))
        self.task_rem_h_8.setText(_translate("MWindow", "M", None))
        self.task_passed_h_5.setText(_translate("MWindow", "Passed Hours:", None))
        self.task_passed_h_6.setText(_translate("MWindow", "Remained Hours:", None))
        self.task_passed_h_2.setText(_translate("MWindow", "0", None))
        self.task_rem_h_2.setText(_translate("MWindow", "20", None))
        self.add_new_time_2.setText(_translate("MWindow", "Add Time", None))
        self.delete_task_2.setText(_translate("MWindow", "X", None))
        self.task_rem_h_9.setText(_translate("MWindow", "M", None))
        self.task_passed_h_7.setText(_translate("MWindow", "Passed Hours:", None))
        self.task_passed_h_8.setText(_translate("MWindow", "Remained Hours:", None))
        self.task_passed_h_3.setText(_translate("MWindow", "0", None))
        self.task_rem_h_3.setText(_translate("MWindow", "20", None))
        self.add_new_time_3.setText(_translate("MWindow", "Add Time", None))
        self.delete_task_3.setText(_translate("MWindow", "X", None))
        self.task_rem_h_10.setText(_translate("MWindow", "M", None))
        self.task_passed_h_9.setText(_translate("MWindow", "Passed Hours:", None))
        self.task_passed_h_10.setText(_translate("MWindow", "Remained Hours:", None))
        self.task_passed_h_4.setText(_translate("MWindow", "0", None))
        self.task_rem_h_4.setText(_translate("MWindow", "20", None))
        self.add_new_time_4.setText(_translate("MWindow", "Add Time", None))
        self.delete_task_4.setText(_translate("MWindow", "X", None))
        self.task_rem_h_11.setText(_translate("MWindow", "M", None))
        self.task_passed_h_11.setText(_translate("MWindow", "Passed Hours:", None))
        self.task_passed_h_12.setText(_translate("MWindow", "Remained Hours:", None))
        self.actionNew_Task.setText(_translate("MWindow", "New Task", None))
        self.actionDelete_Task.setText(_translate("MWindow", "Delete Task", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MWindow = QtGui.QMainWindow()
    ui = Ui_MWindow()
    ui.setupUi(MWindow)
    MWindow.show()
    sys.exit(app.exec_())

